#pragma config(Motor,  motorA,          Large,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          Midium,        tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define dc 100

#define speed 100

task main()
{
	// hairetunoookisa == dc
	int large[100], midium[100], i = 0;
	bool aveFlag = false;
	float ave[2] = {0, 0};
	memset(large, 0, dc);
	memset(midium, 0, dc);
	setMotorSpeed(Large, speed);
	setMotorSpeed(Midium, speed);
	delay(100);
	displayTextLine(1, "Large: 1            Midium: 4");
	while (1) {
		large[i] = getMotorRPM(Large);
		midium[i] = getMotorRPM(Midium);
		if (aveFlag) {
			int sum[2] = {0, 0};
			for (int l = 0; l < dc; l++) {
				sum[0] += large[l];
				sum[1] += midium[l];
			}
			ave[0] = sum[0] / (float) dc;
			ave[1] = sum[1] / (float) dc;
		}
		displayBigTextLine(4, "1: %d", large[i]);
		displayTextLine(6, "              ave: %6.2f", ave[0]);
		displayBigTextLine(8, "4: %d", midium[i]);
		displayTextLine(10, "              ave: %6.2f", ave[1]);
		i++;
		if (i == 100) {
			if (!aveFlag) {
				aveFlag = true;
				playTone(1000, 8);
			}
			i = 0;
		}
		delay(25);
	}
}
