#pragma config(Sensor, S1,     LTcolor,        sensorEV3_Color)
#pragma config(Sensor, S2,     RTcolor,        sensorEV3_Color)
#pragma config(Sensor, S3,     flont,          sensorEV3_Color)
#pragma config(Sensor, S4,     port,           sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          back,          tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define WIDTH 13.5
#define HEIGHT 6.2
#include "I2C_arduino_v2.h"
#include "rap.h"
#include "nan.h"
Trace trace;
Trace trace2;
task main()
{
	while(1)
		int a=0,b=0 ;
		I2CSetUp(S4);
		pinMode(ANALOG,A0);
		pinMode(ANALOG,A1);
		pinMode(DIGITAL,D0);
		initTrace(trace,0.05,0.33,2.20);
		initTrace(trace2,0.15,2.6,24.0);
			while(1)
			{
					tracePID(trace2,65);
					displayTextLine(6,"%d",getmotorRPM(back));
					displayTextLine(1,"%d",getCRLR());
					displayTextLine(2,"%d",getCRLL());
					displayTextLine(4,"%d",getCRNF());
					int a0 =analogRead(A0);
					int a1 =analogRead(A1);
					int d0 =digitalRead(D0);
					displayTextLine(1,"%d",d0);
					delay(20);

					if(getCRLR()<=10&&getCRLL()<=10||getCRLR()<=10&&getCRLF()<=10||getCRLL()<=10&&getCRLF()<=10)
		      {
		      	if(getCRLF()!=0)
		      {
			      	drive(0);
			      	if(a0<=20)
			      		turn2(0,60);
			      	else if(a1<=20)
			      		turn2(0,-60);
			      	else
			      		delay(100);
			      	senti(1.0,-60);
							drive(25);
							checker();
							drive(0);
							clearTimer(T1);
				 			while(1)
				 				{
					 				tracePID(trace2,60);
					 				if(time1[T1]>=2000)
					 					break;
					 			}
					 }
					 	else
					 	{
					 		clearTimer(T1);
				 			while(1)
				 				{
					 				tracePID(trace2,60);
					 				if(time1[T1]>=1000)
					 					break;
					 			}
					 	}
					}
					if (d0==1)
					{
						touch();
						clearTimer(T1);
				 		while(1)
				 		{
					 		tracePID(trace2,60);
					 		if(time1[T1]>=3000)
					 			break;
					 	}
					}
				if(getMotorRPM(back)<=5)
						{
							a++;
						if(a>=150)
							{
								boost();
								a=0;
							}
						}
				else
				{
					a--;
					if(a<0)
						a=0;
				}
				if(getCRLR()>=60&&getCRLL()>=60&&getCRLF()>=60)
				{
					b++;
					if(b>=500)
					{
						drive(-60);
						delay(2000);
						drive(0);
						b=0;
					}
				}
				else
					{
						b=0;
					}
			}
}
